<a href="https://colab.research.google.com/github/Varshithanelli/pytorch-fundamentals/blob/main/pytorch_fundamentals_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [3]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
x.argmin()

tensor(0)

In [5]:
x[0]

tensor(0)

In [6]:
x.argmax()

tensor(9)

In [7]:
x[9]

tensor(90)

In [8]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [11]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [12]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [14]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [15]:
x_stacked=torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [16]:
x_reshaped.shape

torch.Size([1, 9])

In [17]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
x_reshaped.squeeze().shape

torch.Size([9])

In [21]:
x_original = torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [23]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

indexing  (selecting data from tensors)

In [24]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [25]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
x[0][0]

tensor([1, 2, 3])

In [27]:
x[0][0][0]

tensor(1)

In [28]:
print(x[0][2][2])
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


In [29]:
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [30]:
array.dtype

dtype('float64')

In [31]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [32]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [34]:
#reproductability
torch.rand(3,3)

tensor([[0.7160, 0.5801, 0.5851],
        [0.1180, 0.7237, 0.2675],
        [0.0783, 0.2926, 0.2979]])

In [35]:
import torch
a=torch.rand(3,4)
b=torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.7972, 0.5160, 0.6118, 0.8678],
        [0.7405, 0.3836, 0.1551, 0.7897],
        [0.6402, 0.5452, 0.1366, 0.0611]])
tensor([[0.5815, 0.9563, 0.6391, 0.3550],
        [0.9995, 0.3900, 0.8160, 0.0296],
        [0.7625, 0.8388, 0.9143, 0.1895]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [37]:
#randome reproductable tensors
import torch
seed=42
torch.manual_seed(seed)

c=torch.rand(3,4)
d=torch.rand(3,4)

print(c)
print(d)
print(c==d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
