<a href="https://colab.research.google.com/github/Varshithanelli/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX=torch.tensor([[7,8],
                           [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([9, 8])

In [14]:
TENSOR=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
random_tensor=torch.rand(10,10)
random_tensor

tensor([[0.8929, 0.8468, 0.5765, 0.6661, 0.2589, 0.8284, 0.4835, 0.9623, 0.8750,
         0.1327],
        [0.4277, 0.7738, 0.2805, 0.9635, 0.2439, 0.5519, 0.7433, 0.6324, 0.0580,
         0.2369],
        [0.1296, 0.4481, 0.2566, 0.0752, 0.0037, 0.7915, 0.3466, 0.8357, 0.1913,
         0.9419],
        [0.1454, 0.2188, 0.3890, 0.6649, 0.3504, 0.8572, 0.3543, 0.8005, 0.2237,
         0.6667],
        [0.1906, 0.9164, 0.2490, 0.4126, 0.3887, 0.5446, 0.0760, 0.1534, 0.8575,
         0.5449],
        [0.8102, 0.0694, 0.8791, 0.4909, 0.9551, 0.1596, 0.9251, 0.8424, 0.4685,
         0.7643],
        [0.3958, 0.7783, 0.4022, 0.0097, 0.8794, 0.7889, 0.6010, 0.5459, 0.0419,
         0.1361],
        [0.0817, 0.5703, 0.5934, 0.9979, 0.9207, 0.2276, 0.9871, 0.8060, 0.0114,
         0.0770],
        [0.5866, 0.1797, 0.8461, 0.2657, 0.2749, 0.6083, 0.1460, 0.8389, 0.4368,
         0.1951],
        [0.0647, 0.7572, 0.0042, 0.4331, 0.7385, 0.2023, 0.2242, 0.1048, 0.1065,
         0.9944]])

In [22]:
random_tensor.ndim

2

In [23]:
r=torch.rand(size=(224,224,3))
r.shape,r.ndim

(torch.Size([224, 224, 3]), 3)